### ISSUE TITLE
Review Dependencies

### ISSUE THREAD

**Issue by cjhr95** [MissouriMRR/compakt#2]
# Review Dependencies

## Problem
We need to run through the installed dependencies and verify that they are actually being used or will be useful in the near future.

## Solution
Review packages installed by @Lmyszka4

**Comment by ghost** [comment]
Dev Dependencies List (Name + Brief Description)

- @sveltejs/adapter-cloudflare - cloudflare deployment
- _@sveltejs/kit_ - organizes project and adds qol integrations
- _@typescript-eslint/eslint-plugin_ - code style suggestions for typescript
- _@typescript-eslint/parser_ - typescript compatibility for eslint
- _esbuild_ - quick bundling
- _eslint_ - enforces coding style, highlights programming and formatting errors
- _eslint-config-prettier_ - resolves conflicts with prettier package
- _eslint-plugin-svelt_ - svelte compatibility for eslint
- _prettier_ - formats code
- _prettier-plugin-svelte_ - svelte compatibility for prettier
- svelte - renders ui elements
- _svelte-check_ - checks programming errors in svelte
- _tslib_ - typescript helper functions
- typescript - compiler for typescript in 
- vite - building app for testing

_Unnecessary but organizational / quality of life_

Analysis:

Because all of these are developer dependencies, they won't add latency to the end-user's access, only to the initial installation of the project.

Non-Necessary Dependencies:
- Sveltejs/kit can be kept as a project organizational tool.
- Eslint, prettier, and svelte-check (and cross-compatibilities) should be kept in parallel, as each will add an extra layer of code-style enforcement and error checking.
- Esbuild should be kept to optimize production build.
- Tslib will contain utility functionalities that will likely be accessed in future features.

The rest are dependencies that are necessary to running and deploying the project.
